In [38]:
import numpy as np
import pandas as pd
import scipy.sparse as sp
from numpy.linalg import norm
from collections import Counter, defaultdict
from scipy.sparse import csr_matrix

In [39]:
df = pd.read_csv('/Users/sudhani/Downloads/combine.csv')

/Users/sudhani/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (19,55,112,123,124,125,128,129,130,133,139,140,141) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [40]:
df.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,8400,8400,8400.0,36 months,9.75%,270.06,B,B3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,12000,12000,12000.0,36 months,7.89%,375.43,A,A5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,28000,28000,28000.0,36 months,7.39%,869.57,A,A4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,10000,10000,10000.0,36 months,13.67%,340.18,C,C3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,20000,20000,20000.0,36 months,11.99%,664.20,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
filterList1 = list(df)

In [42]:
df.shape

(1048575, 145)

In [43]:
df.index.values

array([      0,       1,       2, ..., 1048572, 1048573, 1048574])

In [44]:
# df.loan_amnt == 8400

In [45]:
# new_header = df.iloc[0] #grab the first row for the header
# df = df[1:] #take the data less the header row
# df.columns = new_header #set the header row as the df header

In [46]:
# df1 = df[['loan_amnt', 'funded_amnt']]
df1 = df.iloc[:,0:2]

In [47]:
df1.head()

   id  member_id
0 NaN        NaN
1 NaN        NaN
2 NaN        NaN
3 NaN        NaN
4 NaN        NaN

In [48]:
df.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,8400,8400,8400.0,36 months,9.75%,270.06,B,B3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,12000,12000,12000.0,36 months,7.89%,375.43,A,A5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,28000,28000,28000.0,36 months,7.39%,869.57,A,A4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,10000,10000,10000.0,36 months,13.67%,340.18,C,C3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,20000,20000,20000.0,36 months,11.99%,664.20,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
int(df.memory_usage(deep=False).sum()/1000000)

1216

In [50]:
# check_null = df.isnull().sum(axis=0).sort_values(ascending=False)/float(len(df))
# df.drop(check_null[check_null>0.6].index, axis=1, inplace=True)

In [51]:
df = df.loc[df.count(1) > df.shape[1]/2, df.count(0) > df.shape[0]/2]

In [52]:
df.shape

(1048575, 103)

In [53]:
filterList2 = list(df)

In [54]:
unmatched_items_10 = [d for d in filterList1 if d not in filterList2]

In [55]:
unmatched_items_10

['id',
 'member_id',
 'url',
 'desc',
 'mths_since_last_record',
 'mths_since_last_major_derog',
 'annual_inc_joint',
 'dti_joint',
 'verification_status_joint',
 'mths_since_recent_bc_dlq',
 'mths_since_recent_revol_delinq',
 'revol_bal_joint',
 'sec_app_earliest_cr_line',
 'sec_app_inq_last_6mths',
 'sec_app_mort_acc',
 'sec_app_open_acc',
 'sec_app_revol_util',
 'sec_app_open_act_il',
 'sec_app_num_rev_accts',
 'sec_app_chargeoff_within_12_mths',
 'sec_app_collections_12_mths_ex_med',
 'sec_app_mths_since_last_major_derog',
 'hardship_type',
 'hardship_reason',
 'hardship_status',
 'deferral_term',
 'hardship_amount',
 'hardship_start_date',
 'hardship_end_date',
 'payment_plan_start_date',
 'hardship_length',
 'hardship_dpd',
 'hardship_loan_status',
 'orig_projected_additional_accrued_interest',
 'hardship_payoff_balance_amount',
 'hardship_last_payment_amount',
 'debt_settlement_flag_date',
 'settlement_status',
 'settlement_date',
 'settlement_amount',
 'settlement_percentage',
 'settlement_term']

In [56]:
print(df.isnull().sum())

loan_amnt                          0
funded_amnt                        0
funded_amnt_inv                    0
term                               0
int_rate                           0
installment                        0
grade                              0
sub_grade                          0
emp_title                      75519
emp_length                     74478
home_ownership                     0
annual_inc                         0
verification_status                0
issue_d                            0
loan_status                        0
pymnt_plan                         0
purpose                            0
title                          23173
zip_code                           1
addr_state                         0
dti                              999
delinq_2yrs                        0
earliest_cr_line                   0
inq_last_6mths                     1
mths_since_last_delinq        522770
open_acc                           0
pub_rec                            0
revol_bal                          0
revol_util                       930
total_acc                          0
                               ...
mo_sin_rcnt_rev_tl_op              0
mo_sin_rcnt_tl                     0
mort_acc                           0
mths_since_recent_bc           12027
mths_since_recent_inq         118691
num_accts_ever_120_pd              0
num_actv_bc_tl                     0
num_actv_rev_tl                    0
num_bc_sats                        0
num_bc_tl                          0
num_il_tl                          0
num_op_rev_tl                      0
num_rev_accts                      0
num_rev_tl_bal_gt_0                0
num_sats                           0
num_tl_120dpd_2m               48345
num_tl_30dpd                       0
num_tl_90g_dpd_24m                 0
num_tl_op_past_12m                 0
pct_tl_nvr_dlq                     1
percent_bc_gt_75               12779
pub_rec_bankruptcies               0
tax_liens                          0
tot_hi_cred_lim                    0
total_bal_ex_mort                  0
total_bc_limit                     0
total_il_high_credit_limit         0
hardship_flag                      0
disbursement_method                0
debt_settlement_flag               0
Length: 103, dtype: int64

In [57]:
df.dtypes

loan_amnt                       int64
funded_amnt                     int64
funded_amnt_inv               float64
term                           object
int_rate                       object
installment                   float64
grade                          object
sub_grade                      object
emp_title                      object
emp_length                     object
home_ownership                 object
annual_inc                    float64
verification_status            object
issue_d                        object
loan_status                    object
pymnt_plan                     object
purpose                        object
title                          object
zip_code                       object
addr_state                     object
dti                           float64
delinq_2yrs                     int64
earliest_cr_line               object
inq_last_6mths                float64
mths_since_last_delinq        float64
open_acc                        int64
pub_rec                         int64
revol_bal                       int64
revol_util                     object
total_acc                       int64
                               ...
mo_sin_rcnt_rev_tl_op           int64
mo_sin_rcnt_tl                  int64
mort_acc                        int64
mths_since_recent_bc          float64
mths_since_recent_inq         float64
num_accts_ever_120_pd           int64
num_actv_bc_tl                  int64
num_actv_rev_tl                 int64
num_bc_sats                     int64
num_bc_tl                       int64
num_il_tl                       int64
num_op_rev_tl                   int64
num_rev_accts                   int64
num_rev_tl_bal_gt_0             int64
num_sats                        int64
num_tl_120dpd_2m              float64
num_tl_30dpd                    int64
num_tl_90g_dpd_24m              int64
num_tl_op_past_12m              int64
pct_tl_nvr_dlq                float64
percent_bc_gt_75              float64
pub_rec_bankruptcies            int64
tax_liens                       int64
tot_hi_cred_lim                 int64
total_bal_ex_mort               int64
total_bc_limit                  int64
total_il_high_credit_limit      int64
hardship_flag                  object
disbursement_method            object
debt_settlement_flag           object
Length: 103, dtype: object

In [58]:
df.dropna(axis=0, thresh=30, inplace=True)
delete_features = ['zip_code', 'policy_code', 'pymnt_plan', 'application_type', 'acc_now_delinq']
df.drop(delete_features , axis=1, inplace=True)

In [59]:
df.shape

(1048575, 98)

In [60]:
df['term'].head()

0     36 months
1     36 months
2     36 months
3     36 months
4     36 months
Name: term, dtype: object

In [61]:
def string_strip(df = df, header = 'term'):
    df[header] = df[header].str.split(' ').str[1]
    return df

In [62]:
df = string_strip(df, 'term')
df['term'].head()

0    36
1    36
2    36
3    36
4    36
Name: term, dtype: object

In [63]:
df['emp_length'] = df['emp_length'].str.extract('(\d+)').astype(float)
df['emp_length'] = df['emp_length'].fillna(df.emp_length.median())

In [64]:
col_dates = df.dtypes[df.dtypes == 'datetime64[ns]'].index
for d in col_dates:
    df[d] = df[d].dt.to_period('M')
print(df['last_pymnt_d'].head())

0    17-Dec
1    18-Oct
2    18-Oct
3    18-Oct
4    18-Aug
Name: last_pymnt_d, dtype: object

In [65]:
df['amount_diff_inv'] = 'same'
df.loc[(df['funded_amnt'] - df['funded_amnt_inv']) > 0,'amount_diff_inv'] = 'low'
df['acc_ratio'] = df.open_acc / df.total_acc

In [66]:
def give_categorical(df = df):
    df['pub_rec_cat'] = 'no'
    df.loc[df['pub_rec']> 0,'pub_rec_cat'] = 'yes'
    df['delinq_2yrs_cat'] = 'no'
    df.loc[df['delinq_2yrs']> 0,'delinq_2yrs_cat'] = 'yes'
    df['inq_last_6mths_cat'] = 'no'
    df.loc[df['inq_last_6mths']> 0,'inq_last_6mths_cat'] = 'yes'
    return df

In [67]:
def get_features():
    features = ['loan_amnt', 'amount_diff_inv', 'term',
            'installment', 'grade','emp_length',
            'home_ownership', 'annual_inc','verification_status',
            'purpose', 'dti', 'delinq_2yrs_cat', 'inq_last_6mths_cat',
            'open_acc', 'pub_rec', 'pub_rec_cat', 'acc_ratio', 'initial_list_status',
            'loan_status','int_rate'
           ]
    return features
# inq_last_6mths_cat

In [68]:
df = give_categorical(df)
f = get_features()

In [69]:
# df['inq_last_6mths_cat']

In [70]:
cat_features = ['term','amount_diff_inv', 'grade', 'home_ownership', 'verification_status', 'purpose', 'delinq_2yrs_cat', 'inq_last_6mths_cat', 'pub_rec_cat', 'initial_list_status']

In [71]:
# df['acc_ratio'] = df.open_acc / loan_data.total_acc
X_clean = df.loc[df.loan_status != 'Current', f]
mask = (X_clean.loan_status == 'Charged Off')
X_clean['target'] = 0
X_clean.loc[mask,'target'] = 1

X_clean.dropna(axis=0, how = 'any', inplace = True)

In [72]:
# X_All.to_csv("Cleaned_8lakh_All_Null_Removed.csv")

In [73]:
X_clean

,loan_amnt,amount_diff_inv,term,installment,grade,emp_length,home_ownership,annual_inc,verification_status,purpose,...,delinq_2yrs_cat,inq_last_6mths_cat,open_acc,pub_rec,pub_rec_cat,acc_ratio,initial_list_status,loan_status,int_rate,target
0,8400,same,36,270.06,B,2.0,MORTGAGE,66000.0,Not Verified,debt_consolidation,...,no,yes,7,0,no,0.318182,w,Fully Paid,9.75%,0
4,20000,same,36,664.20,C,10.0,MORTGAGE,49000.0,Source Verified,debt_consolidation,...,yes,no,8,0,no,0.285714,w,Fully Paid,11.99%,0
5,13625,same,60,326.36,C,1.0,MORTGAGE,50000.0,Not Verified,credit_card,...,no,no,21,0,no,0.291667,w,Fully Paid,15.31%,0
7,15000,same,60,393.50,D,1.0,RENT,63890.0,Not Verified,debt_consolidation,...,no,yes,7,0,no,0.875000,w,Charged Off,19.53%,1
9,12000,same,60,277.18,C,10.0,MORTGAGE,68000.0,Source Verified,credit_card,...,no,yes,12,0,no,0.363636,w,Late (16-30 days),13.67%,0
11,5000,same,36,160.75,B,1.0,OWN,40000.0,Source Verified,debt_consolidation,...,no,yes,25,1,yes,0.555556,w,Fully Paid,9.75%,0
12,5000,same,36,176.51,D,10.0,MORTGAGE,105000.0,Not Verified,debt_consolidation,...,no,no,13,0,no,0.866667,w,Charged Off,16.29%,1
13,4000,same,36,132.84,C,10.0,RENT,36000.0,Verified,debt_consolidation,...,no,no,5,0,no,0.714286,w,Charged Off,11.99%,1
14,24000,same,36,771.60,B,5.0,MORTGAGE,50000.0,Verified,debt_consolidation,...,no,no,8,0,no,0.571429,w,Charged Off,9.75%,1
18,18000,same,36,567.30,B,10.0,OWN,38200.0,Not Verified,credit_card,...,yes,no,19,0,no,0.463415,w,Fully Paid,8.39%,0
19,12000,same,60,277.18,C,10.0,MORTGAGE,40000.0,Not Verified,debt_consolidation,...,no,no,11,1,yes,0.523810,w,Charged Off,13.67%,1
21,8000,same,36,290.23,D,9.0,RENT,50000.0,Source Verified,debt_consolidation,...,no,no,15,0,no,0.600000,w,Charged Off,18.25%,1
23,10000,same,36,336.90,C,10.0,RENT,75000.0,Not Verified,debt_consolidation,...,no,no,10,0,no,0.384615,w,Late (31-120 days),12.99%,0
25,10000,same,36,329.62,B,1.0,RENT,70000.0,Verified,medical,...,no,no,6,1,yes,0.272727,w,Charged Off,11.47%,1
26,6000,same,36,199.26,C,10.0,MORTGAGE,50000.0,Not Verified,other,...,no,yes,12,1,yes,0.666667,f,Fully Paid,11.99%,0
27,30000,same,36,988.86,B,10.0,RENT,130000.0,Source Verified,credit_card,...,no,no,16,0,no,0.695652,w,Late (16-30 days),11.47%,0
30,10000,same,36,315.17,B,7.0,MORTGAGE,45000.0,Verified,credit_card,...,no,no,5,0,no,0.250000,w,Fully Paid,8.39%,0
32,12000,same,36,382.50,B,2.0,MORTGAGE,35000.0,Verified,debt_consolidation,...,yes,no,10,3,yes,0.555556,w,Fully Paid,9.16%,0
33,25000,same,60,549.44,B,1.0,MORTGAGE,93000.0,Source Verified,debt_consolidation,...,no,yes,9,0,no,0.409091,w,Fully Paid,11.47%,0
35,3500,same,36,120.41,C,7.0,MORTGAGE,62000.0,Source Verified,moving,...,no,yes,12,0,no,0.187500,w,Fully Paid,14.46%,0
36,25000,same,60,678.87,E,1.0,RENT,110000.0,Source Verified,debt_consolidation,...,no,yes,14,0,no,0.636364,w,Charged Off,21.18%,1
37,17650,low,36,651.72,D,2.0,RENT,70000.0,Verified,debt_consolidation,...,no,no,6,0,no,0.666667,f,Charged Off,19.53%,1
39,14400,same,36,469.74,B,10.0,MORTGAGE,85000.0,Not Verified,small_business,...,no,no,16,0,no,0.484848,w,Fully Paid,10.75%,0
40,5000,same,36,168.45,C,4.0,OWN,150000.0,Source Verified,other,...,no,yes,15,2,yes,0.483871,f,Fully Paid,12.99%,0
42,15000,same,36,451.73,A,4.0,MORTGAGE,90000.0,Not Verified,home_improvement,...,yes,no,12,0,no,0.521739,w,Fully Paid,5.32%,0
45,30000,same,60,667.19,C,10.0,MORTGAGE,81000.0,Source Verified,debt_consolidation,...,no,no,8,0,no,0.347826,w,Fully Paid,11.99%,0
46,25000,same,60,672.83,E,5.0,RENT,70000.0,Verified,debt_consolidation,...,no,no,18,1,yes,0.486486,w,Charged Off,20.75%,1
48,18000,same,60,400.31,C,6.0,MORTGAGE,100000.0,Verified,debt_consolidation,...,yes,yes,21,0,no,0.525000,w,Fully Paid,11.99%,0
52,35000,same,60,769.22,B,4.0,MORTGAGE,137000.0,Verified,credit_card,...,yes,no,12,0,no,0.444444,w,Fully Paid,11.47%,0
53,5000,same,36,166.05,C,9.0,RENT,80000.0,Not Verified,debt_consolidation,...,no,yes,17,0,no,0.566667,w,Charged Off,11.99%,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048163,6100,same,36,186.10,A,2.0,RENT,100000.0,Not Verified,credit_card,...,no,no,12,0,no,0.800000,w,Fully Paid,6.19%,0
1048164,5000,same,36,184.35,D,3.0,MORTGAGE,110000.0,Not Verified,home_improvement,...,yes,yes,9,0,no,0.290323,f,Fully Paid,19.42%,0
1048183,20200,same,60,485.77,C,6.0,MORTGAGE,90000.0,Not Verified,debt_consolidation,...,no,yes,13,0,no,0.590909,f,Fully Paid,15.49%,0
1048186,9900,same,36,319.78,B,1.0,RENT,55000.0,Not Verified,credit_card,...,no,no,6,0,no,0.666667,w,Late (31-120 days),10.07%,0
1048207,8000,same,36,246.40,A,5.0,MORTGAGE,200000.0,Source Verified,home_improvement,...,no,no,15,0,no,0.468750,w,Fully Paid,6.83%,0
1048225,15500,same,36,496.01,B,10.0,RENT,65000.0,Source Verified,debt_consolidation,...,no,yes,13,0,no,0.590909,w,In Grace Period,9.43%,0
1048227,15000,same,60,353.09,C,1.0,OWN,55000.0,Source Verified,moving,...,no,no,14,1,yes,0.250000,w,Fully Paid,14.52%,0
1048242,15000,same,60,353.09,C,1.0,RENT,134100.0,Not Verified,home_improvement,...,yes,yes,11,0,no,0.687500,w,Fully Paid,14.52%,0
1048274,4000,same,36,124.36,A,10.0,RENT,47835.0,Source Verified,other,...,no,no,9,0,no,0.642857,w,Fully Paid,7.46%,0
1048276,40000,same,36,1282.82,B,7.0,RENT,124546.0,Verified,credit_card,...,no,no,7,0,no,0.466667,w,Fully Paid,9.58%,0
1048286,7500,same,36,233.16,A,10.0,RENT,63710.0,Not Verified,credit_card,...,no,no,8,0,no,0.666667,f,Fully Paid,7.46%,0
1048296,4000,same,36,131.05,B,5.0,RENT,55000.0,Not Verified,debt_consolidation,...,no,yes,7,0,no,0.437500,w,Fully Paid,11.05%,0
1048301,15000,low,36,462.00,A,10.0,RENT,70000.0,Not Verified,other,...,no,yes,12,1,yes,0.428571,f,Fully Paid,6.83%,0
1048334,17000,same,36,528.50,A,10.0,MORTGAGE,136000.0,Not Verified,other,...,no,no,17,0,no,0.435897,w,Fully Paid,7.46%,0
1048353,10000,same,36,332.77,B,8.0,MORTGAGE,35000.0,Not Verified,home_improvement,...,no,yes,5,0,no,0.357143,w,Fully Paid,12.13%,0
1048382,7500,same,36,258.24,C,10.0,MORTGAGE,157600.0,Source Verified,moving,...,yes,no,9,0,no,0.360000,w,Fully Paid,14.52%,0
1048395,16000,same,36,566.16,C,10.0,RENT,68000.0,Verified,other,...,no,yes,28,1,yes,0.823529,w,Fully Paid,16.46%,0
1048403,6000,same,36,188.24,A,1.0,RENT,60000.0,Not Verified,debt_consolidation,...,no,yes,6,0,no,0.750000,w,Fully Paid,8.08%,0
1048417,11000,same,36,355.31,B,6.0,MORTGAGE,170000.0,Source Verified,house,...,no,no,16,0,no,0.320000,w,Fully Paid,10.07%,0
1048436,10000,same,60,238.11,C,10.0,MORTGAGE,50000.0,Verified,debt_consolidation,...,no,no,4,1,yes,0.285714,w,Late (31-120 days),15.04%,0
1048501,36000,same,36,1171.11,B,9.0,RENT,69000.0,Source Verified,other,...,yes,yes,4,0,no,0.307692,w,Fully Paid,10.56%,0
1048510,8000,same,36,261.54,B,10.0,MORTGAGE,70000.0,Source Verified,home_improvement,...,no,yes,6,0,no,0.333333,w,Late (31-120 days),10.90%,0
1048518,8000,same,36,291.03,D,2.0,OWN,15000.0,Not Verified,debt_consolidation,...,yes,no,12,0,no,0.857143,f,Fully Paid,18.45%,0
1048527,8000,same,36,250.99,A,3.0,OWN,80000.0,Not Verified,other,...,no,yes,11,0,no,0.523810,w,Fully Paid,8.08%,0
1048547,10000,same,36,305.09,A,10.0,MORTGAGE,80000.0,Not Verified,home_improvement,...,no,no,11,0,no,0.379310,w,Fully Paid,6.19%,0
1048548,9300,same,36,298.26,B,3.0,OWN,43000.0,Source Verified,credit_card,...,no,no,7,0,no,0.304348,w,Fully Paid,9.58%,0
1048549,12000,same,36,407.69,C,1.0,RENT,48000.0,Source Verified,debt_consolidation,...,no,no,10,0,no,0.588235,w,Late (16-30 days),13.58%,0
1048560,9500,same,36,286.05,A,10.0,MORTGAGE,80000.0,Not Verified,credit_card,...,no,yes,7,0,no,0.411765,w,Fully Paid,5.31%,0
1048568,2000,same,36,72.76,D,4.0,RENT,46000.0,Source Verified,other,...,yes,no,10,0,no,0.625000,w,Fully Paid,18.45%,0
1048573,18000,same,36,585.56,B,10.0,MORTGAGE,113000.0,Source Verified,credit_card,...,no,no,18,0,no,0.473684,w,Fully Paid,10.56%,0

In [74]:
X_clean.shape

(392508, 21)

In [75]:
X_clean.to_csv('example.csv')