In [499]:
import numpy as np
import pandas as pd
import scipy.sparse as sp
from numpy.linalg import norm
from collections import Counter, defaultdict
from scipy.sparse import csr_matrix

In [500]:
df = pd.read_csv('/Users/shripalmodani/Downloads/Downloads/LoanStats_2016Q1.csv', header=1)

/Users/shripalmodani/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2698: DtypeWarning: Columns (0,19) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [501]:
df.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,8400.0,8400.0,8400.0,36 months,9.75%,270.06,B,B3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,12000.0,12000.0,12000.0,36 months,7.89%,375.43,A,A5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,28000.0,28000.0,28000.0,36 months,7.39%,869.57,A,A4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,10000.0,10000.0,10000.0,36 months,13.67%,340.18,C,C3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,20000.0,20000.0,20000.0,36 months,11.99%,664.20,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [463]:
filterList1 = list(df)

In [464]:
df.shape

(133889, 145)

In [465]:
df.index.values

array([     0,      1,      2, ..., 133886, 133887, 133888])

In [466]:
# df.loan_amnt == 8400

In [467]:
# new_header = df.iloc[0] #grab the first row for the header
# df = df[1:] #take the data less the header row
# df.columns = new_header #set the header row as the df header

In [468]:
# df1 = df[['loan_amnt', 'funded_amnt']]
df1 = df.iloc[:,0:2]

In [469]:
df1.head()

    id  member_id
0  NaN        NaN
1  NaN        NaN
2  NaN        NaN
3  NaN        NaN
4  NaN        NaN

In [470]:
df.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,8400.0,8400.0,8400.0,36 months,9.75%,270.06,B,B3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,12000.0,12000.0,12000.0,36 months,7.89%,375.43,A,A5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,28000.0,28000.0,28000.0,36 months,7.39%,869.57,A,A4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,10000.0,10000.0,10000.0,36 months,13.67%,340.18,C,C3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,20000.0,20000.0,20000.0,36 months,11.99%,664.20,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [471]:
int(df.memory_usage(deep=False).sum()/1000000)

155

In [472]:
# check_null = df.isnull().sum(axis=0).sort_values(ascending=False)/float(len(df))
# df.drop(check_null[check_null>0.6].index, axis=1, inplace=True)

In [473]:
df = df.loc[df.count(1) > df.shape[1]/2, df.count(0) > df.shape[0]/2]

In [474]:
df.shape

(133887, 102)

In [475]:
filterList2 = list(df)

In [476]:
unmatched_items_10 = [d for d in filterList1 if d not in filterList2]

In [477]:
unmatched_items_10

['id',
 'member_id',
 'url',
 'desc',
 'mths_since_last_record',
 'next_pymnt_d',
 'mths_since_last_major_derog',
 'annual_inc_joint',
 'dti_joint',
 'verification_status_joint',
 'mths_since_recent_bc_dlq',
 'mths_since_recent_revol_delinq',
 'revol_bal_joint',
 'sec_app_earliest_cr_line',
 'sec_app_inq_last_6mths',
 'sec_app_mort_acc',
 'sec_app_open_acc',
 'sec_app_revol_util',
 'sec_app_open_act_il',
 'sec_app_num_rev_accts',
 'sec_app_chargeoff_within_12_mths',
 'sec_app_collections_12_mths_ex_med',
 'sec_app_mths_since_last_major_derog',
 'hardship_type',
 'hardship_reason',
 'hardship_status',
 'deferral_term',
 'hardship_amount',
 'hardship_start_date',
 'hardship_end_date',
 'payment_plan_start_date',
 'hardship_length',
 'hardship_dpd',
 'hardship_loan_status',
 'orig_projected_additional_accrued_interest',
 'hardship_payoff_balance_amount',
 'hardship_last_payment_amount',
 'debt_settlement_flag_date',
 'settlement_status',
 'settlement_date',
 'settlement_amount',
 'settlement_percentage',
 'settlement_term']

In [478]:
print(df.isnull().sum())

loan_amnt                         0
funded_amnt                       0
funded_amnt_inv                   0
term                              0
int_rate                          0
installment                       0
grade                             0
sub_grade                         0
emp_title                      8981
emp_length                        0
home_ownership                    0
annual_inc                        0
verification_status               0
issue_d                           0
loan_status                       0
pymnt_plan                        0
purpose                           0
title                         10621
zip_code                          0
addr_state                        0
dti                              17
delinq_2yrs                       0
earliest_cr_line                  0
inq_last_6mths                    1
mths_since_last_delinq        64565
open_acc                          0
pub_rec                           0
revol_bal                         0
revol_util                       71
total_acc                         0
                              ...
mo_sin_rcnt_rev_tl_op             0
mo_sin_rcnt_tl                    0
mort_acc                          0
mths_since_recent_bc           1044
mths_since_recent_inq         13798
num_accts_ever_120_pd             0
num_actv_bc_tl                    0
num_actv_rev_tl                   0
num_bc_sats                       0
num_bc_tl                         0
num_il_tl                         0
num_op_rev_tl                     0
num_rev_accts                     0
num_rev_tl_bal_gt_0               0
num_sats                          0
num_tl_120dpd_2m               7621
num_tl_30dpd                      0
num_tl_90g_dpd_24m                0
num_tl_op_past_12m                0
pct_tl_nvr_dlq                    0
percent_bc_gt_75               1129
pub_rec_bankruptcies              0
tax_liens                         0
tot_hi_cred_lim                   0
total_bal_ex_mort                 0
total_bc_limit                    0
total_il_high_credit_limit        0
hardship_flag                     0
disbursement_method               0
debt_settlement_flag              0
Length: 102, dtype: int64

In [479]:
df.dtypes

loan_amnt                     float64
funded_amnt                   float64
funded_amnt_inv               float64
term                           object
int_rate                       object
installment                   float64
grade                          object
sub_grade                      object
emp_title                      object
emp_length                     object
home_ownership                 object
annual_inc                    float64
verification_status            object
issue_d                        object
loan_status                    object
pymnt_plan                     object
purpose                        object
title                          object
zip_code                       object
addr_state                     object
dti                           float64
delinq_2yrs                   float64
earliest_cr_line               object
inq_last_6mths                float64
mths_since_last_delinq        float64
open_acc                      float64
pub_rec                       float64
revol_bal                     float64
revol_util                     object
total_acc                     float64
                               ...
mo_sin_rcnt_rev_tl_op         float64
mo_sin_rcnt_tl                float64
mort_acc                      float64
mths_since_recent_bc          float64
mths_since_recent_inq         float64
num_accts_ever_120_pd         float64
num_actv_bc_tl                float64
num_actv_rev_tl               float64
num_bc_sats                   float64
num_bc_tl                     float64
num_il_tl                     float64
num_op_rev_tl                 float64
num_rev_accts                 float64
num_rev_tl_bal_gt_0           float64
num_sats                      float64
num_tl_120dpd_2m              float64
num_tl_30dpd                  float64
num_tl_90g_dpd_24m            float64
num_tl_op_past_12m            float64
pct_tl_nvr_dlq                float64
percent_bc_gt_75              float64
pub_rec_bankruptcies          float64
tax_liens                     float64
tot_hi_cred_lim               float64
total_bal_ex_mort             float64
total_bc_limit                float64
total_il_high_credit_limit    float64
hardship_flag                  object
disbursement_method            object
debt_settlement_flag           object
Length: 102, dtype: object

In [480]:
df.dropna(axis=0, thresh=30, inplace=True)
delete_features = ['zip_code', 'policy_code', 'pymnt_plan', 'application_type', 'acc_now_delinq']
df.drop(delete_features , axis=1, inplace=True)

In [481]:
df.shape

(133887, 97)

In [482]:
df['term'].head()

0     36 months
1     36 months
2     36 months
3     36 months
4     36 months
Name: term, dtype: object

In [483]:
def string_strip(df = df, header = 'term'):
    df[header] = df[header].str.split(' ').str[1]
    return df

In [484]:
df = string_strip(df, 'term')
df['term'].head()

0    36
1    36
2    36
3    36
4    36
Name: term, dtype: object

In [485]:
df['emp_length'] = df['emp_length'].str.extract('(\d+)').astype(float)
df['emp_length'] = df['emp_length'].fillna(df.emp_length.median())

/Users/shripalmodani/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)
  """Entry point for launching an IPython kernel.

In [486]:
col_dates = df.dtypes[df.dtypes == 'datetime64[ns]'].index
for d in col_dates:
    df[d] = df[d].dt.to_period('M')
print(df['last_pymnt_d'].head())

0    Dec-2017
1    Oct-2018
2    Oct-2018
3    Oct-2018
4    Aug-2018
Name: last_pymnt_d, dtype: object

In [487]:
df['amount_diff_inv'] = 'same'
df.loc[(df['funded_amnt'] - df['funded_amnt_inv']) > 0,'amount_diff_inv'] = 'low'
df['acc_ratio'] = df.open_acc / df.total_acc

In [488]:
def give_categorical(df = df):
    df['pub_rec_cat'] = 'no'
    df.loc[df['pub_rec']> 0,'pub_rec_cat'] = 'yes'
    df['delinq_2yrs_cat'] = 'no'
    df.loc[df['delinq_2yrs']> 0,'delinq_2yrs_cat'] = 'yes'
    df['inq_last_6mths_cat'] = 'no'
    df.loc[df['inq_last_6mths']> 0,'inq_last_6mths_cat'] = 'yes'
    return df

In [489]:
def get_features():
    features = ['loan_amnt', 'amount_diff_inv', 'term',
            'installment', 'grade','emp_length',
            'home_ownership', 'annual_inc','verification_status',
            'purpose', 'dti', 'delinq_2yrs_cat', 'inq_last_6mths_cat',
            'open_acc', 'pub_rec', 'pub_rec_cat', 'acc_ratio', 'initial_list_status',
            'loan_status'
           ]
    return features
# inq_last_6mths_cat

In [490]:
df = give_categorical(df)
f = get_features()

In [496]:
# df['inq_last_6mths_cat']

In [492]:
cat_features = ['term','amount_diff_inv', 'grade', 'home_ownership', 'verification_status', 'purpose', 'delinq_2yrs_cat', 'inq_last_6mths_cat', 'pub_rec_cat', 'initial_list_status']

In [493]:
# df['acc_ratio'] = df.open_acc / loan_data.total_acc
X_clean = df.loc[df.loan_status != 'Current', f]
mask = (X_clean.loan_status == 'Charged Off')
X_clean['target'] = 0
X_clean.loc[mask,'target'] = 1

X_clean.dropna(axis=0, how = 'any', inplace = True)

In [494]:
# X_All.to_csv("Cleaned_8lakh_All_Null_Removed.csv")

In [495]:
X_clean

,loan_amnt,amount_diff_inv,term,installment,grade,emp_length,home_ownership,annual_inc,verification_status,purpose,dti,delinq_2yrs_cat,inq_last_6mths_cat,open_acc,pub_rec,pub_rec_cat,acc_ratio,initial_list_status,loan_status,target
0,8400.0,same,36,270.06,B,2.0,MORTGAGE,66000.0,Not Verified,debt_consolidation,13.84,no,yes,7.0,0.0,no,0.318182,w,Fully Paid,0
4,20000.0,same,36,664.20,C,10.0,MORTGAGE,49000.0,Source Verified,debt_consolidation,15.58,yes,no,8.0,0.0,no,0.285714,w,Fully Paid,0
5,13625.0,same,60,326.36,C,1.0,MORTGAGE,50000.0,Not Verified,credit_card,30.41,no,no,21.0,0.0,no,0.291667,w,Fully Paid,0
7,15000.0,same,60,393.50,D,1.0,RENT,63890.0,Not Verified,debt_consolidation,20.36,no,yes,7.0,0.0,no,0.875000,w,Charged Off,1
9,12000.0,same,60,277.18,C,10.0,MORTGAGE,68000.0,Source Verified,credit_card,17.17,no,yes,12.0,0.0,no,0.363636,w,Late (16-30 days),0
11,5000.0,same,36,160.75,B,1.0,OWN,40000.0,Source Verified,debt_consolidation,10.38,no,yes,25.0,1.0,yes,0.555556,w,Fully Paid,0
12,5000.0,same,36,176.51,D,10.0,MORTGAGE,105000.0,Not Verified,debt_consolidation,9.07,no,no,13.0,0.0,no,0.866667,w,Charged Off,1
13,4000.0,same,36,132.84,C,10.0,RENT,36000.0,Verified,debt_consolidation,16.40,no,no,5.0,0.0,no,0.714286,w,Charged Off,1
14,24000.0,same,36,771.60,B,5.0,MORTGAGE,50000.0,Verified,debt_consolidation,24.46,no,no,8.0,0.0,no,0.571429,w,Charged Off,1
18,18000.0,same,36,567.30,B,10.0,OWN,38200.0,Not Verified,credit_card,24.07,yes,no,19.0,0.0,no,0.463415,w,Fully Paid,0
19,12000.0,same,60,277.18,C,10.0,MORTGAGE,40000.0,Not Verified,debt_consolidation,28.50,no,no,11.0,1.0,yes,0.523810,w,Charged Off,1
21,8000.0,same,36,290.23,D,9.0,RENT,50000.0,Source Verified,debt_consolidation,22.00,no,no,15.0,0.0,no,0.600000,w,Charged Off,1
23,10000.0,same,36,336.90,C,10.0,RENT,75000.0,Not Verified,debt_consolidation,15.09,no,no,10.0,0.0,no,0.384615,w,Late (31-120 days),0
25,10000.0,same,36,329.62,B,1.0,RENT,70000.0,Verified,medical,9.14,no,no,6.0,1.0,yes,0.272727,w,Charged Off,1
26,6000.0,same,36,199.26,C,10.0,MORTGAGE,50000.0,Not Verified,other,19.71,no,yes,12.0,1.0,yes,0.666667,f,Fully Paid,0
27,30000.0,same,36,988.86,B,10.0,RENT,130000.0,Source Verified,credit_card,16.56,no,no,16.0,0.0,no,0.695652,w,Late (16-30 days),0
30,10000.0,same,36,315.17,B,7.0,MORTGAGE,45000.0,Verified,credit_card,20.91,no,no,5.0,0.0,no,0.250000,w,Fully Paid,0
32,12000.0,same,36,382.50,B,2.0,MORTGAGE,35000.0,Verified,debt_consolidation,48.25,yes,no,10.0,3.0,yes,0.555556,w,Fully Paid,0
33,25000.0,same,60,549.44,B,1.0,MORTGAGE,93000.0,Source Verified,debt_consolidation,15.78,no,yes,9.0,0.0,no,0.409091,w,Fully Paid,0
35,3500.0,same,36,120.41,C,7.0,MORTGAGE,62000.0,Source Verified,moving,35.81,no,yes,12.0,0.0,no,0.187500,w,Fully Paid,0
36,25000.0,same,60,678.87,E,1.0,RENT,110000.0,Source Verified,debt_consolidation,18.80,no,yes,14.0,0.0,no,0.636364,w,Charged Off,1
37,17650.0,low,36,651.72,D,2.0,RENT,70000.0,Verified,debt_consolidation,13.63,no,no,6.0,0.0,no,0.666667,f,Charged Off,1
39,14400.0,same,36,469.74,B,10.0,MORTGAGE,85000.0,Not Verified,small_business,28.11,no,no,16.0,0.0,no,0.484848,w,Fully Paid,0
40,5000.0,same,36,168.45,C,4.0,OWN,150000.0,Source Verified,other,10.13,no,yes,15.0,2.0,yes,0.483871,f,Fully Paid,0
42,15000.0,same,36,451.73,A,4.0,MORTGAGE,90000.0,Not Verified,home_improvement,7.75,yes,no,12.0,0.0,no,0.521739,w,Fully Paid,0
45,30000.0,same,60,667.19,C,10.0,MORTGAGE,81000.0,Source Verified,debt_consolidation,14.07,no,no,8.0,0.0,no,0.347826,w,Fully Paid,0
46,25000.0,same,60,672.83,E,5.0,RENT,70000.0,Verified,debt_consolidation,23.01,no,no,18.0,1.0,yes,0.486486,w,Charged Off,1
48,18000.0,same,60,400.31,C,6.0,MORTGAGE,100000.0,Verified,debt_consolidation,20.41,yes,yes,21.0,0.0,no,0.525000,w,Fully Paid,0
52,35000.0,same,60,769.22,B,4.0,MORTGAGE,137000.0,Verified,credit_card,30.17,yes,no,12.0,0.0,no,0.444444,w,Fully Paid,0
53,5000.0,same,36,166.05,C,9.0,RENT,80000.0,Not Verified,debt_consolidation,22.55,no,yes,17.0,0.0,no,0.566667,w,Charged Off,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133830,7225.0,same,36,237.30,B,10.0,MORTGAGE,55000.0,Source Verified,home_improvement,14.44,no,yes,10.0,0.0,no,0.666667,f,Charged Off,1
133831,35000.0,same,36,1204.40,C,3.0,MORTGAGE,110000.0,Source Verified,debt_consolidation,15.81,no,no,10.0,0.0,no,0.217391,w,Fully Paid,0
133834,19000.0,same,60,456.11,D,1.0,RENT,110000.0,Not Verified,small_business,0.27,no,no,3.0,0.0,no,0.157895,w,Fully Paid,0
133835,12000.0,same,36,394.12,B,10.0,MORTGAGE,75000.0,Verified,home_improvement,23.34,no,no,14.0,0.0,no,0.482759,w,Fully Paid,0
133836,20000.0,same,36,637.58,B,6.0,MORTGAGE,85000.0,Source Verified,debt_consolidation,9.31,yes,yes,8.0,1.0,yes,0.666667,w,Fully Paid,0
133837,30000.0,low,60,778.06,E,7.0,MORTGAGE,122000.0,Source Verified,debt_consolidation,28.44,yes,yes,18.0,0.0,no,0.514286,f,Charged Off,1
133839,35000.0,same,36,1172.39,C,10.0,OWN,125000.0,Verified,credit_card,17.90,no,yes,20.0,0.0,no,0.444444,w,Charged Off,1
133841,20000.0,same,60,518.71,E,6.0,RENT,82000.0,Source Verified,debt_consolidation,21.33,yes,yes,8.0,0.0,no,0.250000,w,Charged Off,1
133842,19700.0,same,36,633.45,B,4.0,MORTGAGE,73746.0,Verified,debt_consolidation,13.03,no,yes,8.0,1.0,yes,0.571429,f,Fully Paid,0
133844,30000.0,low,60,769.83,E,10.0,MORTGAGE,95000.0,Verified,home_improvement,31.35,yes,yes,20.0,0.0,no,0.526316,w,Charged Off,1
133845,30000.0,same,36,924.81,A,3.0,MORTGAGE,300000.0,Verified,debt_consolidation,8.92,no,no,7.0,0.0,no,0.368421,f,Fully Paid,0
133846,8000.0,same,36,260.55,B,6.0,MORTGAGE,63510.0,Verified,credit_card,24.51,no,no,11.0,1.0,yes,0.297297,f,Fully Paid,0
133847,8000.0,same,36,265.68,C,6.0,OWN,30000.0,Not Verified,credit_card,34.84,no,yes,16.0,0.0,no,0.727273,w,Charged Off,1
133848,24000.0,same,36,788.24,B,1.0,RENT,96031.0,Verified,other,20.52,no,no,20.0,0.0,no,0.833333,w,Fully Paid,0
133849,24000.0,same,36,788.24,B,1.0,RENT,75000.0,Verified,debt_consolidation,22.98,no,yes,12.0,0.0,no,0.600000,w,Fully Paid,0
133852,3975.0,same,36,143.43,D,4.0,RENT,60000.0,Verified,other,16.36,no,no,4.0,0.0,no,0.307692,w,Fully Paid,0
133853,7000.0,same,36,240.88,C,1.0,OWN,70000.0,Source Verified,debt_consolidation,25.37,no,yes,7.0,0.0,no,0.583333,f,In Grace Period,0
133857,5200.0,same,36,184.24,D,1.0,RENT,38000.0,Verified,car,5.43,no,yes,6.0,0.0,no,0.500000,w,Fully Paid,0
133858,19000.0,low,36,630.99,C,8.0,RENT,48000.0,Verified,other,22.75,no,yes,9.0,1.0,yes,0.692308,f,Fully Paid,0
133865,16800.0,same,36,520.74,A,1.0,RENT,62000.0,Verified,debt_consolidation,23.40,no,no,7.0,0.0,no,0.777778,w,Fully Paid,0
133868,12600.0,same,60,326.79,E,8.0,RENT,35000.0,Verified,debt_consolidation,35.97,yes,no,9.0,0.0,no,0.642857,f,Fully Paid,0
133869,35000.0,same,60,907.73,E,6.0,MORTGAGE,90000.0,Verified,debt_consolidation,18.23,no,yes,19.0,0.0,no,0.193878,w,Fully Paid,0
133870,25000.0,low,36,916.28,E,4.0,RENT,62000.0,Verified,debt_consolidation,19.63,no,no,10.0,0.0,no,0.555556,f,Charged Off,1
133872,5000.0,same,36,168.91,C,4.0,RENT,42000.0,Source Verified,car,6.08,yes,yes,17.0,0.0,no,0.944444,w,Fully Paid,0
133873,5000.0,same,36,174.34,D,4.0,MORTGAGE,60000.0,Source Verified,debt_consolidation,32.34,no,yes,14.0,0.0,no,0.482759,w,Charged Off,1
133877,6000.0,same,36,244.22,G,6.0,RENT,20000.0,Verified,debt_consolidation,29.11,no,yes,20.0,0.0,no,0.645161,w,Charged Off,1
133878,6000.0,same,36,204.11,C,10.0,RENT,85000.0,Verified,moving,2.85,no,yes,4.0,1.0,yes,0.500000,f,Fully Paid,0
133879,24100.0,same,60,618.43,E,10.0,RENT,65000.0,Source Verified,debt_consolidation,17.54,no,no,7.0,0.0,no,0.437500,w,Charged Off,1
133880,4000.0,same,36,127.52,B,5.0,MORTGAGE,46800.0,Source Verified,credit_card,19.18,no,no,12.0,0.0,no,0.444444,w,Fully Paid,0
133884,14400.0,same,60,328.98,C,10.0,RENT,47000.0,Verified,credit_card,19.64,no,yes,7.0,0.0,no,0.368421,w,Charged Off,1